;(function($,_,undefined){"use strict";ips.controller.mixin('events','core.front.core.commentFeed',true,function(){const originalSetup=this.setup;this.setup=(()=>{originalSetup.bind(this)();this.on('change','[name=live_topic_select_question]',this.addLiveTopicQuestion);}).bind(this);const originalQuoteComment=this.quoteComment;this.quoteComment=((e,data)=>{originalQuoteComment.bind(this)(e,data);if(this.scope.find('[data-role="replyArea"] [data-ipsEditorv5]').length){try{if(IpsDataLayerConfig&&IpsDataLayerConfig._events.content_quote.enabled){let context=IpsDataLayerContext||{};$('body').trigger('ipsDataLayer',{_key:'content_quote',_properties:context,_analytics_full_only:true});}}catch(e){}};}).bind(this);this.addLiveTopicQuestion=((e,data)=>{const questionId=this.scope.find('[name=live_topic_select_question]').val();const _self=this;if(questionId){ips.getAjax()(this.scope.find('[data-role="replyArea"] form').attr('action'),{data:'do=getQuestionQuoteDataForEditor&ltqid='+questionId+'&csrfKey='+ips.getSetting('csrfKey'),type:'get'}).done(function(response){ips.ui.editorv5.getObjWithInit(_self.scope.find('[data-role="replyArea"] [data-ipsEditorv5]'),function(editor){editor.insertQuotes([response]);});});}}).bind(this);this.addMultiQuote=((e,data)=>{var mqData=this._getMultiQuoteData();var key=data.contentapp+'-'+data.contenttype+'-'+data.contentcommentid;if(_.size(mqData)==this._maximumMultiQuote){ips.ui.alert.show({type:'alert',icon:'warn',message:ips.pluralize(ips.getString('maxmultiquote'),this._maximumMultiQuote),callbacks:{ok:function(){$("button[data-mqId='"+data.button+"']").removeClass('ipsButton--secondary').addClass('ipsButton--simple').removeAttr('data-mqActive').html(ips.templates.render('core.posts.multiQuoteOff'));}}});return false;}
mqData[key]=data;ips.utils.db.set('mq','data',mqData);try{if(IpsDataLayerConfig&&IpsDataLayerConfig._events.content_quote.enabled){let context=IpsDataLayerContext||{};$('body').trigger('ipsDataLayer',{_key:'content_quote',_properties:context,_analytics_full_only:true,});}}catch(e){}
this._buildMultiQuote(_.size(mqData));}).bind(this);});}(jQuery,_));;
;(function($,_,undefined){"use strict";ips.controller.mixin('events','core.front.core.commentFeed',true,function(){let currentCount,maxCount,_currentlyInEditingMode;const currentlyInEditingMode=()=>{if(_currentlyInEditingMode===undefined){_currentlyInEditingMode=!!window.location.href.toString().match(/^.*#editTopicSummary$/)}
return _currentlyInEditingMode};const postScoreAverage=()=>parseFloat(feedBlurb()?.dataset.postScoreAverage||'');const postIsInSummary=(postElem)=>{if(Number.isNaN(postScoreAverage())){return false;}
if(postElem.querySelector(`[data-commentid]`)?.dataset?.postForceInSummary){return true;}
if(isNaN(parseFloat(postElem.querySelector(`[data-commentid]`)?.dataset?.postScore))){return false;}
return parseFloat(postElem.querySelector(`[data-commentid]`).dataset.postScore)>=postScoreAverage();}
const feedID=this.scope.get(0).dataset.feedid
const feedBlurb=()=>feedID?document.querySelector(`[data-role="topicSummaryBlurb"][data-feedid="${encodeURIComponent(feedID)}"]`):undefined
const editSummaryButton=()=>feedID?feedBlurb()?.querySelector(`[href='#editTopicSummary']`):undefined
const editSummaryExitButton=()=>feedID?feedBlurb()?.querySelector(`[href='#editTopicSummaryExit']`):undefined
const getPostElements=()=>[...this.elem.querySelectorAll('[data-ips-hook="postWrapper"]')].filter(el=>el.querySelector(`.ipsEntry__content[data-commentid]`));const setupEditingMode=e=>{_currentlyInEditingMode=true;ips.utils.history.replaceState({editing:true},`topic_summary_${feedID}`,window.location.href.toString().replace(/^.*#[a-z0-9\-_\s#]*$/i,'#editTopicSummary'))
editSummaryExitButton()?.ipsShow();editSummaryButton()?.ipsHide();currentCount=parseInt(feedBlurb()?.dataset.summarySize);maxCount=parseInt(feedBlurb()?.dataset.maxSummarySize);for(const el of getPostElements()){if(!el.querySelector('.ipsTopicSummary_post_toggle')){const toggleMenu=document.createElement('div');toggleMenu.classList.add('ipsTopicSummary_post_toggle');if(!currentlyInEditingMode()){toggleMenu.ipsHide();}
toggleMenu.innerHTML=ips.templates.render('topic_summary_toggle_post');el.querySelector(`.ipsEntry__content .ipsEntry__meta`).appendChild(toggleMenu);el.querySelector(`[data-ips-hook="topicAuthorColumn"] .ipsEntry__header-align`)?.appendChild(toggleMenu.cloneNode(true));el.querySelectorAll('.ipsTopicSummary_post_toggle [data-role]').forEach(_el=>{_el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();addOrRemovePostInSummary(el,_el.dataset.role!=='remove')})})}
if(!postIsInSummary(el)){el.classList.add('ipsTopicSummary_post__disabled')
el.querySelector('[data-ips-hook="postContent"]').ipsDisable();el.querySelectorAll('.ipsTopicSummary_post_toggle [data-role="add"]').ipsShow();el.querySelectorAll('.ipsTopicSummary_post_toggle [data-role="remove"]').ipsHide();}else{el.querySelectorAll('.ipsTopicSummary_post_toggle [data-role="add"]').ipsHide();el.querySelectorAll('.ipsTopicSummary_post_toggle [data-role="remove"]').ipsShow();}
el.querySelectorAll('.ipsTopicSummary_post_toggle').ipsShow();el.querySelectorAll('.ipsEntry__meta .ipsEntry__topButton--ellipsis').ipsHide();el.querySelectorAll('[data-ips-hook="topicAuthorColumn"] :is(.ipsEntry__topButton--ellipsis, .ipsEntry__topButton--profile)').ipsHide();}
if((currentCount>=maxCount)){this.elem.querySelectorAll('.ipsTopicSummary_post_toggle [data-role="add"]').ipsDisable({message:ips.getString('max_topic_summary_size_reached')});}else{this.elem.querySelectorAll('.ipsTopicSummary_post_toggle [data-role="add"]').ipsEnable();}
this.elem.querySelectorAll(`[data-ipspagination] [data-page][href]`).forEach(el=>{el.setAttribute('href',el.getAttribute('href').replace(/^.*#[a-z0-9\-_\s]*$/,'')+'#editTopicSummary')})}
const exitEditingMode=e=>{e?.preventDefault();_currentlyInEditingMode=false;const url=window.location.href.toString().replace(/#editTopicSummary$/,'')
ips.utils.history.replaceState({editing:false},`topic_summary_${feedID}`,url)
editSummaryExitButton()?.ipsHide();editSummaryButton()?.ipsShow();for(const el of getPostElements()){el.classList.remove('ipsTopicSummary_post__disabled');el.querySelector('[data-ips-hook="postContent"]').ipsEnable();el.querySelectorAll('.ipsTopicSummary_post_toggle').ipsHide();el.querySelectorAll('.ipsEntry__meta .ipsEntry__topButton--ellipsis').ipsShow();el.querySelectorAll('[data-ips-hook="topicAuthorColumn"] :is(.ipsEntry__topButton--ellipsis, .ipsEntry__topButton--profile)').ipsShow();}
this.elem.querySelectorAll(`[data-ipspagination] [data-page][href]`).forEach(el=>{el.setAttribute('href',el.getAttribute('href').replace(/^.*#editTopicSummary$/,''))})}
const commentId=postEl=>parseInt(postEl.querySelector(`[data-commentid]`)?.dataset?.commentid);const addOrRemovePostInSummary=(post,add=true)=>{const url=window.location.href.toString();ips.getAjax()(url,{data:{comment:commentId(post),do:'addOrRemovePostFromSummary',add:!!add},method:"POST"}).done(data=>{if(add){post.dataset.postForceInSummary='1';post.classList.remove('ipsTopicSummary_post__disabled');post.querySelector('[data-ips-hook="postContent"]').ipsEnable();post.querySelectorAll('.ipsTopicSummary_post_toggle [data-role="add"]').ipsHide();post.querySelectorAll('.ipsTopicSummary_post_toggle [data-role="remove"]').ipsShow();}else{post.classList.add('ipsTopicSummary_post__disabled');post.dataset.postScore=""+data?.postScore;post.querySelector('[data-ips-hook="postContent"]').ipsDisable();delete post.dataset.postForceInSummary;post.querySelectorAll('.ipsTopicSummary_post_toggle [data-role="add"]').ipsShow();post.querySelectorAll('.ipsTopicSummary_post_toggle [data-role="remove"]').ipsHide();}
currentCount=data.count
maxCount=data.max;if((currentCount>=maxCount)){this.elem.querySelectorAll('.ipsTopicSummary_post_toggle [data-role="add"]').ipsDisable({message:ips.getString('max_topic_summary_size_reached')});}else{this.elem.querySelectorAll('.ipsTopicSummary_post_toggle [data-role="add"]').ipsEnable();}}).fail(err=>{if(err.userMessage){ips.ui.alert.show({message:err.userMessage,buttons:{ok:ips.getString('ok')}});alert(`An error occurred: \n${err.userMessage}`);}})}
const init=()=>{editSummaryButton()?.addEventListener('click',setupEditingMode);editSummaryExitButton()?.addEventListener('click',exitEditingMode);if(currentlyInEditingMode()){setupEditingMode();}else{exitEditingMode();}}
if(editSummaryButton()&&editSummaryExitButton()){this.after('initialize',init)
$(document).on('contentChange',init)}});}(jQuery,_));;
;(function($,_,undefined){"use strict";ips.controller.mixin('events','core.front.core.dataLayer',true,function(){const originalSetup=this.setup;this.setup=(()=>{originalSetup.bind(this)();if(!(ipsSettings.features&&ipsSettings.features.analytics_full)){return;}
this.on('menuItemSelected',this.sortFilter);}).bind(this);const originalHandleEvent=this.handleEvent.bind(this);this.handleEvent=((evt,event)=>{if((event._analytics_full_only)&&!(ipsSettings.features&&ipsSettings.features.analytics_full)){return;}
return originalHandleEvent(evt,event);}).bind(this);const originalHandleProperties=this.handleProperties.bind(this);this.handleProperties=((evt,event)=>{if((event._analytics_full_only)&&!(ipsSettings.features&&ipsSettings.features.analytics_full)){return;}
return originalHandleProperties(evt,event);}).bind(this);this.sortFilter=function(event,data=event.detail){let item=(data.selectable)?$(data.selectedItems[Object.keys(data.selectedItems)[0]]):null;let parent=$(data.menuElem);let action=null;let properties={};if(!item?.data instanceof Function){return;}
if(parent.attr('id').includes('elSortBy')){action='sort';properties.sort_by=item?.data()?.ipsmenuvalue;properties.sort_direction=({asc:'asc',desc:'desc'})[(item?.data().sortdirection||ips.utils.url.getParam('sortdirection'))?.toLowerCase()||'asc'];}else if(parent.attr('id').includes('elFilterBy')){action='filter_add';properties['filter_title']=item.data().ipsmenuvalue;}
if(!properties.filter_title||!properties.sort_by){return;}
let typeMap={forums:'topic',blogs:'entry',calendar:'event',gallery:'image'};let areaKey=IpsDataLayerConfig._properties.community_area.formatted_name;let area=IpsDataLayerContext[areaKey];if(area){properties['content_type']=typeMap[area]||null;}
this.scope.trigger('ipsDataLayer',{_key:action,_properties:properties,_analytics_full_only:true});};});}(jQuery,_));;
;(function($,_){"use strict";ips.controller.mixin('events','forums.front.forum.flow',true,function(){this.toggleFilters=((e)=>{e.preventDefault();var link=$(e.currentTarget);var id=link.attr('data-node-id');var parentId=link.attr('data-parent-id');var hasChildren=link.attr('data-has-children');let action='filter_add';if(_.indexOf(this._ids,id)==-1){this.childSelect(id,false);}else{action='filter_remove';this.childUnselect(id);}
try{if(!window.IpsDataLayerConfig&&IpsDataLayerConfig){let item=$(e.currentTarget).find('.cForumMiniList__title');let label=(item?item.text():$(e.currentTarget).text()).trim(['\n','\t']).split('\n')[0];let url=$(e.currentTarget).attr('href')||null;let properties={filter_title:label,community_area:'forums',content_area:'forums',content_type:'topic',content_container_id:id,content_container_url:url,content_container_name:label,content_container_type:'forum'};this.scope.trigger('ipsDataLayer',{_key:action,_properties:properties,_analytics_full_only:true});}}catch(e){}
this._updateButtonText();$(document).trigger('updateTableURL',{[this.urlParam]:_.uniq(_.values(this._ids)).join(',')});}).bind(this);});}(jQuery,_));;
;(function($,_,undefined){"use strict";ips.controller.mixin('questLeaderboard','core.global.core.table',true,function(){this._timer=null;this._searchField=null;this._curSearchValue='';this._currentValue='';this.after('initialize',function(){this.on('focus','[data-role="tableSearch"]',this.startLiveSearch);this.on('blur','[data-role="tableSearch"]',this.endLiveSearch);});this.before('setup',function(){this._searchField=this.scope.find('[data-role="tableSearch"]');this.scope.find('[data-role="tableSearch"]').removeClass('ipsHide').show();});this.around('_getUrlParams',function(origFn){return _.extend(origFn(),{quicksearch:this._getSearchValue()||''});});this.after('_handleStateChanges',function(state){if(!_.isUndefined(state.data.quicksearch)&&state.data.quicksearch!=this._urlParams.quicksearch){this._updateSearch(state.data.quicksearch);}});this.startLiveSearch=function(e){this._timer=setInterval(_.bind(this._checkSearchValue,this),500);};this.endLiveSearch=function(e){clearInterval(this._timer);};this._checkSearchValue=function(){var val=this._searchField.val();if(this._currentValue!=val){this.updateURL({quicksearch:val,page:1});this._currentValue=val;document.trigger('contentChange',[this.scope])}};this._updateSearch=function(searchValue){this._searchField.val(searchValue);};this._getSearchValue=function(){if(ips.utils.url.getParam('quicksearch')){return ips.utils.url.getParam('quicksearch');}
return this.scope.find('[data-role="tableSearch"]').val();};});}(jQuery,_));;